# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x62\x61sic.proto\"*\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"&\n\x08\x46ileBody\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\"7\n\x0bPredictBody\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04guid\x18\x03 \x01(\t\"\x18\n\x08GuidInfo\x12\x0c\n\x04guid\x18\x01 \x01(\t\"\x1b\n\x0bTrainResult\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"!\n\x11PredictResultFile\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x32(\n\x04\x46ile\x12 \n\x06upload\x12\t.FileBody\x1a\t.Response(\x01\x32+\n\x05Train\x12\"\n\x05train\x12\t.GuidInfo\x1a\x0c.TrainResult0\x01\x32\x46\n\rPredictResult\x12\x35\n\rpredictResult\x12\x0c.PredictBody\x1a\x12.PredictResultFile(\x01\x30\x01\x62\x06proto3')
)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='Response.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=57,
)


_FILEBODY = _descriptor.Descriptor(
  name='FileBody',
  full_name='FileBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='FileBody.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='FileBody.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=97,
)


_PREDICTBODY = _descriptor.Descriptor(
  name='PredictBody',
  full_name='PredictBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='PredictBody.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='PredictBody.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guid', full_name='PredictBody.guid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=154,
)


_GUIDINFO = _descriptor.Descriptor(
  name='GuidInfo',
  full_name='GuidInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='GuidInfo.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=180,
)


_TRAINRESULT = _descriptor.Descriptor(
  name='TrainResult',
  full_name='TrainResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='TrainResult.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=209,
)


_PREDICTRESULTFILE = _descriptor.Descriptor(
  name='PredictResultFile',
  full_name='PredictResultFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='PredictResultFile.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['FileBody'] = _FILEBODY
DESCRIPTOR.message_types_by_name['PredictBody'] = _PREDICTBODY
DESCRIPTOR.message_types_by_name['GuidInfo'] = _GUIDINFO
DESCRIPTOR.message_types_by_name['TrainResult'] = _TRAINRESULT
DESCRIPTOR.message_types_by_name['PredictResultFile'] = _PREDICTRESULTFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'basic_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

FileBody = _reflection.GeneratedProtocolMessageType('FileBody', (_message.Message,), dict(
  DESCRIPTOR = _FILEBODY,
  __module__ = 'basic_pb2'
  # @@protoc_insertion_point(class_scope:FileBody)
  ))
_sym_db.RegisterMessage(FileBody)

PredictBody = _reflection.GeneratedProtocolMessageType('PredictBody', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTBODY,
  __module__ = 'basic_pb2'
  # @@protoc_insertion_point(class_scope:PredictBody)
  ))
_sym_db.RegisterMessage(PredictBody)

GuidInfo = _reflection.GeneratedProtocolMessageType('GuidInfo', (_message.Message,), dict(
  DESCRIPTOR = _GUIDINFO,
  __module__ = 'basic_pb2'
  # @@protoc_insertion_point(class_scope:GuidInfo)
  ))
_sym_db.RegisterMessage(GuidInfo)

TrainResult = _reflection.GeneratedProtocolMessageType('TrainResult', (_message.Message,), dict(
  DESCRIPTOR = _TRAINRESULT,
  __module__ = 'basic_pb2'
  # @@protoc_insertion_point(class_scope:TrainResult)
  ))
_sym_db.RegisterMessage(TrainResult)

PredictResultFile = _reflection.GeneratedProtocolMessageType('PredictResultFile', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTRESULTFILE,
  __module__ = 'basic_pb2'
  # @@protoc_insertion_point(class_scope:PredictResultFile)
  ))
_sym_db.RegisterMessage(PredictResultFile)



_FILE = _descriptor.ServiceDescriptor(
  name='File',
  full_name='File',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=246,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='File.upload',
    index=0,
    containing_service=None,
    input_type=_FILEBODY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILE)

DESCRIPTOR.services_by_name['File'] = _FILE


_TRAIN = _descriptor.ServiceDescriptor(
  name='Train',
  full_name='Train',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=288,
  serialized_end=331,
  methods=[
  _descriptor.MethodDescriptor(
    name='train',
    full_name='Train.train',
    index=0,
    containing_service=None,
    input_type=_GUIDINFO,
    output_type=_TRAINRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAIN)

DESCRIPTOR.services_by_name['Train'] = _TRAIN


_PREDICTRESULT = _descriptor.ServiceDescriptor(
  name='PredictResult',
  full_name='PredictResult',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=333,
  serialized_end=403,
  methods=[
  _descriptor.MethodDescriptor(
    name='predictResult',
    full_name='PredictResult.predictResult',
    index=0,
    containing_service=None,
    input_type=_PREDICTBODY,
    output_type=_PREDICTRESULTFILE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTRESULT)

DESCRIPTOR.services_by_name['PredictResult'] = _PREDICTRESULT

# @@protoc_insertion_point(module_scope)
